# Generated by Django 3.0.5 on 2020-10-10 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_name', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('number_of_forks', models.IntegerField()),
                ('number_of_courses', models.IntegerField()),
                ('details', models.CharField(max_length=2000)),
                ('stars', models.IntegerField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
        migrations.CreateModel(
            name='Fork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('forker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
                ('roadmap_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sun_api.Roadmap')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50)),
                ('course_link', models.URLField()),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('course_description', models.CharField(max_length=255)),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sun_api.Roadmap')),
            ],
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('link', models.URLField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
    ]
